engines:
  credo:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - elixir:
      	  mass_threshold: 30
ratings:
  paths:
  - app/**
  - lib/**
  - "**.ex"
  - "**.exs"
- _build
